spring:
  datasource:
    url: jdbc:mariadb://sejong-binary.com/homepage?allowPublicKeyRetrieval=true&useSSL=false
    username: leegusrb
    password: dlgusrb
    driver-class-name: org.mariadb.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

#logging.level:
#  org.hibernate.SQL: debug
